### ISSUE TITLE
app已经加载了，但是设置好没效果

### ISSUE THREAD

**Issue by seraph758** [Xposed-Modules-Repo/top.trangle.mbga#1]
![Screenshot_2024-01-27-18-48-38-55_c04b2410b7d5171ab7b04575f928d980](https://github.com/Xposed-Modules-Repo/top.trangle.mbga/assets/10000026/044c7268-6cf1-448d-94d9-a6cc3d9cbf48)
![Screenshot_2024-01-27-18-48-35-49_18fe6f119af5ae2c728d929083699df1](https://github.com/Xposed-Modules-Repo/top.trangle.mbga/assets/10000026/d851b155-31b0-4532-bedc-876150c177c0)
[LSPosed_2024-01-27T18_53_27.067810.zip](https://github.com/Xposed-Modules-Repo/top.trangle.mbga/files/14072008/LSPosed_2024-01-27T18_53_27.067810.zip)

**Comment by seraph758** [comment]
系统一加氧14，app版本和你测试的版本一样

**Comment by cledwynl** [comment]
有点麻，我两个手机，现在一个行一个不行，今天研究一下

**Comment by cledwynl** [comment]
更新了v1.0.1，可以试试看。我这边之前不生效的手机测试没问题了

**Comment by cledwynl** [comment]
@seraph758 我先关闭这个issue了，如果你那还是不行再reopen哈
